# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS2PYImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CS2PYImage(object):
    def setupUi(self, CS2PYImage):
        CS2PYImage.setObjectName("CS2PYImage")
        CS2PYImage.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CS2PYImage)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ReadImage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ReadImage.setGeometry(QtCore.QRect(290, 350, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_ReadImage.setFont(font)
        self.btn_ReadImage.setObjectName("btn_ReadImage")
        CS2PYImage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CS2PYImage)
        self.statusbar.setObjectName("statusbar")
        CS2PYImage.setStatusBar(self.statusbar)

        self.retranslateUi(CS2PYImage)
        QtCore.QMetaObject.connectSlotsByName(CS2PYImage)

    def retranslateUi(self, CS2PYImage):
        _translate = QtCore.QCoreApplication.translate
        CS2PYImage.setWindowTitle(_translate("CS2PYImage", "CS2PYImage"))
        self.btn_ReadImage.setText(_translate("CS2PYImage", "ReadImage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CS2PYImage = QtWidgets.QMainWindow()
    ui = Ui_CS2PYImage()
    ui.setupUi(CS2PYImage)
    CS2PYImage.show()
    sys.exit(app.exec_())
