# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(400, 600)
        Main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_PyQt = QtWidgets.QPushButton(Main)
        self.btn_PyQt.setGeometry(QtCore.QRect(140, 160, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_PyQt.setFont(font)
        self.btn_PyQt.setObjectName("btn_PyQt")
        self.lbl_PyQt = QtWidgets.QLabel(Main)
        self.lbl_PyQt.setGeometry(QtCore.QRect(70, 80, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_PyQt.setFont(font)
        self.lbl_PyQt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_PyQt.setObjectName("lbl_PyQt")
        self.lbl_Name = QtWidgets.QLabel(Main)
        self.lbl_Name.setGeometry(QtCore.QRect(70, 260, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_Name.setFont(font)
        self.lbl_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Name.setObjectName("lbl_Name")
        self.lbl_Age = QtWidgets.QLabel(Main)
        self.lbl_Age.setGeometry(QtCore.QRect(70, 330, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_Age.setFont(font)
        self.lbl_Age.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Age.setObjectName("lbl_Age")
        self.lbl_Gender = QtWidgets.QLabel(Main)
        self.lbl_Gender.setGeometry(QtCore.QRect(70, 400, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_Gender.setFont(font)
        self.lbl_Gender.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Gender.setObjectName("lbl_Gender")
        self.btn_Thread = QtWidgets.QPushButton(Main)
        self.btn_Thread.setGeometry(QtCore.QRect(90, 480, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_Thread.setFont(font)
        self.btn_Thread.setObjectName("btn_Thread")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "PyQt"))
        self.btn_PyQt.setText(_translate("Main", "Hello PyQt"))
        self.lbl_PyQt.setText(_translate("Main", "Hello PyQt"))
        self.lbl_Name.setText(_translate("Main", "Name : "))
        self.lbl_Age.setText(_translate("Main", "Age :"))
        self.lbl_Gender.setText(_translate("Main", "Gender : "))
        self.btn_Thread.setText(_translate("Main", "Threading"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QDialog()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
