# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThreadTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThreadTest(object):
    def setupUi(self, ThreadTest):
        ThreadTest.setObjectName("ThreadTest")
        ThreadTest.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ThreadTest)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Thread1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Thread1.setGeometry(QtCore.QRect(200, 220, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lbl_Thread1.setFont(font)
        self.lbl_Thread1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_Thread1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Thread1.setObjectName("lbl_Thread1")
        self.btn_Thread1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Thread1.setGeometry(QtCore.QRect(180, 330, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_Thread1.setFont(font)
        self.btn_Thread1.setObjectName("btn_Thread1")
        self.lbl_Thread2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Thread2.setGeometry(QtCore.QRect(470, 210, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lbl_Thread2.setFont(font)
        self.lbl_Thread2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_Thread2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Thread2.setObjectName("lbl_Thread2")
        self.btn_Thread2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Thread2.setGeometry(QtCore.QRect(450, 320, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_Thread2.setFont(font)
        self.btn_Thread2.setObjectName("btn_Thread2")
        ThreadTest.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ThreadTest)
        self.statusbar.setObjectName("statusbar")
        ThreadTest.setStatusBar(self.statusbar)

        self.retranslateUi(ThreadTest)
        QtCore.QMetaObject.connectSlotsByName(ThreadTest)

    def retranslateUi(self, ThreadTest):
        _translate = QtCore.QCoreApplication.translate
        ThreadTest.setWindowTitle(_translate("ThreadTest", "測試多執行續"))
        self.lbl_Thread1.setText(_translate("ThreadTest", "0"))
        self.btn_Thread1.setText(_translate("ThreadTest", "Thread1"))
        self.lbl_Thread2.setText(_translate("ThreadTest", "0"))
        self.btn_Thread2.setText(_translate("ThreadTest", "Thread2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThreadTest = QtWidgets.QMainWindow()
    ui = Ui_ThreadTest()
    ui.setupUi(ThreadTest)
    ThreadTest.show()
    sys.exit(app.exec_())
