# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RS232.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RS232(object):
    def setupUi(self, RS232):
        RS232.setObjectName("RS232")
        RS232.resize(470, 587)
        self.centralwidget = QtWidgets.QWidget(RS232)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_SendMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_SendMessage.setGeometry(QtCore.QRect(10, 80, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.txt_SendMessage.setFont(font)
        self.txt_SendMessage.setObjectName("txt_SendMessage")
        self.cmb_Port = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_Port.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.cmb_Port.setFont(font)
        self.cmb_Port.setObjectName("cmb_Port")
        self.btn_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Connect.setGeometry(QtCore.QRect(160, 10, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_Connect.setFont(font)
        self.btn_Connect.setObjectName("btn_Connect")
        self.btn_Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Disconnect.setGeometry(QtCore.QRect(310, 10, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_Disconnect.setFont(font)
        self.btn_Disconnect.setObjectName("btn_Disconnect")
        self.btn_SendMessage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SendMessage.setGeometry(QtCore.QRect(310, 80, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.btn_SendMessage.setFont(font)
        self.btn_SendMessage.setObjectName("btn_SendMessage")
        self.rtb_ReceiveMessage = QtWidgets.QTextEdit(self.centralwidget)
        self.rtb_ReceiveMessage.setGeometry(QtCore.QRect(10, 150, 451, 411))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.rtb_ReceiveMessage.setFont(font)
        self.rtb_ReceiveMessage.setObjectName("rtb_ReceiveMessage")
        RS232.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RS232)
        self.statusbar.setObjectName("statusbar")
        RS232.setStatusBar(self.statusbar)

        self.retranslateUi(RS232)
        QtCore.QMetaObject.connectSlotsByName(RS232)

    def retranslateUi(self, RS232):
        _translate = QtCore.QCoreApplication.translate
        RS232.setWindowTitle(_translate("RS232", "RS232"))
        self.btn_Connect.setText(_translate("RS232", "連線"))
        self.btn_Disconnect.setText(_translate("RS232", "斷開"))
        self.btn_SendMessage.setText(_translate("RS232", "傳送"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RS232 = QtWidgets.QMainWindow()
    ui = Ui_RS232()
    ui.setupUi(RS232)
    RS232.show()
    sys.exit(app.exec_())
