# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hello_PyQt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *  # 使用 from xxx import * 可以不用打模組前綴名稱
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets

from Controller.Hello_PyQt import *

class Frm_PyQtMVC(QMainWindow): # PyQtMVC 繼承 QMainWindow 
    def __init__(self, parent = None): # 如果沒有父視窗預設為 null
        super(QMainWindow, self).__init__(parent) # 查找 QMainWindow 的所有父類, 並且帶入父視窗執行所有初始化函式
        self.ui = Ui_PyQtMVC() # 剛從 .ui 轉換成 .py 黨的類別
        self.ui.setupUi(self) # 初始化視窗內部元件
        self.linkEvent() # 創立事件連結

    def linkEvent(self):
        ## 在這裡加入視窗內部元件對應的事件
        self.ui.btn_PyQt.clicked.connect(lambda: btn_PyQt_Clicked(self)) # 註冊按鈕事件

class Ui_PyQtMVC(object):
    def setupUi(self, PyQtMVC):
        PyQtMVC.setObjectName("PyQtMVC")
        PyQtMVC.resize(400, 600)
        PyQtMVC.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_PyQt = QtWidgets.QPushButton(PyQtMVC)
        self.btn_PyQt.setGeometry(QtCore.QRect(140, 160, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_PyQt.setFont(font)
        self.btn_PyQt.setObjectName("btn_PyQt")
        self.lbl_PyQt = QtWidgets.QLabel(PyQtMVC)
        self.lbl_PyQt.setGeometry(QtCore.QRect(70, 80, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_PyQt.setFont(font)
        self.lbl_PyQt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_PyQt.setObjectName("lbl_PyQt")
        self.lbl_Name = QtWidgets.QLabel(PyQtMVC)
        self.lbl_Name.setGeometry(QtCore.QRect(70, 260, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_Name.setFont(font)
        self.lbl_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Name.setObjectName("lbl_Name")
        self.lbl_Age = QtWidgets.QLabel(PyQtMVC)
        self.lbl_Age.setGeometry(QtCore.QRect(70, 330, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_Age.setFont(font)
        self.lbl_Age.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Age.setObjectName("lbl_Age")
        self.lbl_Gender = QtWidgets.QLabel(PyQtMVC)
        self.lbl_Gender.setGeometry(QtCore.QRect(70, 400, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.lbl_Gender.setFont(font)
        self.lbl_Gender.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Gender.setObjectName("lbl_Gender")

        self.retranslateUi(PyQtMVC)
        QtCore.QMetaObject.connectSlotsByName(PyQtMVC)

    def retranslateUi(self, PyQtMVC):
        _translate = QtCore.QCoreApplication.translate
        PyQtMVC.setWindowTitle(_translate("PyQtMVC", "PyQtMVC"))
        self.btn_PyQt.setText(_translate("PyQtMVC", "Hello PyQt"))
        self.lbl_PyQt.setText(_translate("PyQtMVC", "Hello PyQt"))
        self.lbl_Name.setText(_translate("PyQtMVC", "Name : "))
        self.lbl_Age.setText(_translate("PyQtMVC", "Age :"))
        self.lbl_Gender.setText(_translate("PyQtMVC", "Gender : "))

